### ISSUE TITLE
Fails to autoload with undefined variable pjsua_start

### ISSUE THREAD

**Issue by drGrove** [rexroni/weechat-voipms#1]
After installing weechat-dev and libpjproject-dev and running `make`.

I symlinked the file in the appropriate location and attempted to load the plugin.

The error received was: `Undefined Symbol: pjsua_start`

Details:
Ubuntu 18.04.1 LTS
Weechat-dev 2.3-1 amd64
libpjproject-dev 2.7.2\~dfsg-1 amd64
gcc (Ubuntu 7.3.0-27ubuntu1\~18.04) 7.3.0

**Comment by rexroni** [comment]
That seems odd.  Maybe you have an LD_LIBRARY_PATH issue, since you can compile against the libpjsua library but it's not being loaded at runtime.  Or perhaps you have two versions of pjsua, and you are compiling against one but loading another one or something.  Or maybe you just need to try running `sudo ldconfig` or something?

I'm not quite sure what to do to help you troubleshoot.  A reboot perhaps, to make really sure all your terminals are running with an up-to-date environment?  Or maybe you can try and force loading the correct library at runtime, something like:

    LD_PRELOAD=/usr/lib/libpjsua.so weechat

Or you might try putting `libpjsua2.so` there in place of the `libpjsua.so`.

Let me know what happens.

Also, I realize I wrote some basic chat history features that greatly improved the usability of this plugin, but I haven't pushed them to the github repo.  I'll push them this evening.

**Comment by drGrove** [comment]
I'll pull in the latest changes as well. What's interesting is that neither of those show up in /usr/lib

**Comment by rexroni** [comment]
Then that is your problem.  I run on Parabola Linux (an offshoot of ArchLinux) and my `libpjsua.so` library is in `/usr/lib`.  Since the makefile works for you, you should be able to run 

    pkgconf --libs libpjproject

on your machine to find the location of the `libpjsua.so`, and once you have that directory, you can start weechat like this:

    LD_LIBRARY_PATH=/path/to/where/the/libraries/are weechat

or you can edit that variable in your `~/.bashrc` with a line like:

    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/where/the/libraries/are

After the `~/.bashrc` edit, the environment of all of your future `bash` sessions will have the LD_LIBRARY_PATH variable set so that you can call weechat normally.

**Comment by drGrove** [comment]
Using LD_PRELOAD seems to fix the loading issue, running into some random crashes and some fun bugs with texting Google Fi accounts, but this issue is now resolved IMO. Thanks for all your help!

**Comment by rexroni** [comment]
No problem!  If the bugs you are seeing are with my voip plugin, please file them as such, and I'll work on tracking them down and fixing them.
